version: 2

jobs:
  build:
    docker:
      - image: cimg/android:2024.01.1-ndk
    environment:
      # JVM_OPTS: -Xmx3200m
      GRADLE_VERSION: 8.13
      GRADLE_HOME: gradle-8.13
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: Install Gradle
          command: |
            wget https://services.gradle.org/distributions/gradle-$GRADLE_VERSION-bin.zip
            unzip gradle-$GRADLE_VERSION-bin.zip
      - run:
          name: Download Dependencies
          command: $GRADLE_HOME/bin/gradle androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}
      - run:
          name: Build
          command: $GRADLE_HOME/bin/gradle assembleDebug
      - run:
          name: Run Tests
          command: $GRADLE_HOME/bin/gradle lint test
      - store_artifacts: # for display in Artifacts: https://circleci.com/docs/2.0/artifacts/
          path: build/reports
          destination: reports
      - store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
          path: build/test-results
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples
